SELECT TEAMS.NAME
FROM TEAMS
WHERE TEAM_ID in
(SELECT HOST_TEAM_ID
FROM MATCHES
GROUP BY HOST_TEAM_ID
HAVING COUNT(HOST_TEAM_ID) > 3) or TEAM_ID in
(SELECT guest_TEAM_ID
FROM MATCHES
GROUP BY guest_TEAM_ID
HAVING COUNT(guest_TEAM_ID) > 3)